name: CI

on: [push]

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "1.3.2"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ZD_PAT }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: CI - 0. Set up Python and poetry ${{ env.PYTHON_VERSION }}
      uses: ./.github/actions/setup-python-poetry
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        poetry-version: ${{ env.POETRY_VERSION }}
    - name: CI - 1. Running test suites
      run: poetry run bash ./bin/run_tests.sh
    - name: CI - 2. Updating API docs
      id: export_api
      run: |
        set +e
        poetry run python ./bin/export_api_docs.py
        git diff-index --quiet HEAD --
        CALL_DEPLOY="$?"
        echo "CALL_DEPLOY=$CALL_DEPLOY" >> $GITHUB_OUTPUT
    - name: CI - 2. Updating API docs ECHO
      run: |
        echo "CALL_DEPLOY=${{ steps.export_api.outputs.CALL_DEPLOY }}"
    - name: CI - 3. Pushing API docs changes
      if: steps.export_api.outputs.CALL_DEPLOY
      env:
        GITHUB_TOKEN: ${{ secrets.ZD_PAT }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add ./index.html
        git commit -m "Update API docs" || true
        git push || true
