name: CI

on: [push]

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "1.3.2"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python and poetry ${{ env.PYTHON_VERSION }}
      uses: ./.github/actions/setup-python-poetry
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        poetry-version: ${{ env.POETRY_VERSION }}
    - name: Tests
      run: poetry run bash ./bin/run_tests.sh
    - name: Replacing API docs
      run: |
        poetry run python ./bin/export_api_docs.py
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Replacing API docs Automation"
        git push
