name: CI

on: [push]

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "1.3.2"

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python and poetry ${{ env.PYTHON_VERSION }}
      uses: ./.github/actions/setup-python-poetry
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        poetry-version: ${{ env.POETRY_VERSION }}
    - name: Pytest
      run: poetry run bash ./bin/run_tests.sh
  pylint:
    if: ${{ always() }}
    needs: pytest
    runs-on: ubuntu-latest
    steps:
    - name: Pylint
      run: poetry run pylint $(git ls-files '*.py')    
  black:
    if: ${{ always() }}
    needs: pytest
    runs-on: ubuntu-latest
    steps:
      - name: Black
        run: poetry run black . --check