name: CI

on: [push]

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "1.3.2"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - name: CI - 0. Set up Python and poetry ${{ env.PYTHON_VERSION }}
      uses: ./.github/actions/setup-python-poetry
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        poetry-version: ${{ env.POETRY_VERSION }}
    - name: CI - 1. Running test suites
      run: poetry run bash ./bin/run_tests.sh
    - name: CI - 2. Updating API docs
      id: export_api
      run: |
        poetry run python ./bin/export_api_docs.py
        echo "CALL_DEPLOY=$(git diff-index --quiet HEAD --)"
        echo "CALL_DEPLOY2=$(git diff --quiet HEAD --)"
        echo "CALL_DEPLOY=$(git diff-index --quiet HEAD --)" >> "$GITHUB_OUTPUT"
        echo "CALL_DEPLOY3=${{ steps.export_api.outputs.CALL_DEPLOY }}"
    - name: CI - 2. Updating API docs ECHO
      run: |
        echo "CALL_DEPLOY4=${{ steps.export_api.outputs.CALL_DEPLOY }}"
    outputs:
      call_deploy: ${{ steps.export_api.outputs.CALL_DEPLOY }}
      
  push_api_docs:
    runs-on: ubuntu-latest
    needs:
      - test
    if: needs.test.outputs.call_deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: CI - 3. Pushing API docs changes
      run: |  
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add ./index.html
        git commit -m "Update API docs" || true
        git push || true
