name: Pylint

on: [push]

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "1.3.2"

jobs:
  run_pytest:
    name: Running pytest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python and poetry ${{ env.PYTHON_VERSION }}
      uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          poetry-version: ${{ env.POETRY_VERSION }}
    - name: Running pytest
        run: |
          pylint $(git ls-files '*.py')